version: '2'
services:
    wggateway-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/WgGateway/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=WgGateway
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
